default:
  app:
    name: Hello world application
    version: 0.1.0

  broker:
    kafka:
      clientId: helloWorldApplication
      brokers:
        # - localhost:29092
        - localhost:9092
      consumerOptions:
        groupId: helloWorldApplication
      topics:
        # - hello
        # - goodbye
        - Helloworldapplication-0.1.1-hello
      topicSeparator: # "__"
      topicPrefix:

development:

test:

staging:

production:
  broker:
    kafka:
      ssl:
        rejectUnauthorized: true
